# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import logicmonitor
from logicmonitor.rest import ApiException
from logicmonitor.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = logicmonitor.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_ack_alert_by_id(self):
        """
        Test case for ack_alert_by_id

        ack alert by id
        """
        pass

    def test_ack_collector_down_alert_by_id(self):
        """
        Test case for ack_collector_down_alert_by_id

        ack collector down alert
        """
        pass

    def test_add_admin(self):
        """
        Test case for add_admin

        add admin
        """
        pass

    def test_add_alert_note_by_id(self):
        """
        Test case for add_alert_note_by_id

        add alert note
        """
        pass

    def test_add_alert_rule(self):
        """
        Test case for add_alert_rule

        add alert rule
        """
        pass

    def test_add_api_token_by_admin_id(self):
        """
        Test case for add_api_token_by_admin_id

        add apiToken by admin
        """
        pass

    def test_add_collector(self):
        """
        Test case for add_collector

        add collector
        """
        pass

    def test_add_collector_group(self):
        """
        Test case for add_collector_group

        add collector group
        """
        pass

    def test_add_dashboard(self):
        """
        Test case for add_dashboard

        add dashboard
        """
        pass

    def test_add_dashboard_group(self):
        """
        Test case for add_dashboard_group

        add dashboard group
        """
        pass

    def test_add_device(self):
        """
        Test case for add_device

        add a new device
        """
        pass

    def test_add_device_datasource_instance(self):
        """
        Test case for add_device_datasource_instance

        add device instance 
        """
        pass

    def test_add_device_datasource_instance_group(self):
        """
        Test case for add_device_datasource_instance_group

        add device datasource instance group 
        """
        pass

    def test_add_device_group(self):
        """
        Test case for add_device_group

        add device group
        """
        pass

    def test_add_device_group_property(self):
        """
        Test case for add_device_group_property

        add device group property
        """
        pass

    def test_add_device_property(self):
        """
        Test case for add_device_property

        add device property
        """
        pass

    def test_add_role(self):
        """
        Test case for add_role

        add role
        """
        pass

    def test_add_service_group(self):
        """
        Test case for add_service_group

        add service group
        """
        pass

    def test_delete_admin_by_id(self):
        """
        Test case for delete_admin_by_id

        delete admin
        """
        pass

    def test_delete_alert_rule_by_id(self):
        """
        Test case for delete_alert_rule_by_id

        delete alert rule
        """
        pass

    def test_delete_api_token_by_id(self):
        """
        Test case for delete_api_token_by_id

        delete apiToken 
        """
        pass

    def test_delete_collector_by_id(self):
        """
        Test case for delete_collector_by_id

        delete collector
        """
        pass

    def test_delete_collector_group_by_id(self):
        """
        Test case for delete_collector_group_by_id

        delete collector group
        """
        pass

    def test_delete_dashboard_by_id(self):
        """
        Test case for delete_dashboard_by_id

        delete dashboard
        """
        pass

    def test_delete_dashboard_group_by_id(self):
        """
        Test case for delete_dashboard_group_by_id

        delete dashboard group
        """
        pass

    def test_delete_device(self):
        """
        Test case for delete_device

        delete a device
        """
        pass

    def test_delete_device_group_by_id(self):
        """
        Test case for delete_device_group_by_id

        delete device group
        """
        pass

    def test_delete_device_group_property_by_name(self):
        """
        Test case for delete_device_group_property_by_name

        delete device group property
        """
        pass

    def test_delete_device_property_by_name(self):
        """
        Test case for delete_device_property_by_name

        delete device  property
        """
        pass

    def test_delete_role_by_id(self):
        """
        Test case for delete_role_by_id

        delete role
        """
        pass

    def test_delete_service_group_by_id(self):
        """
        Test case for delete_service_group_by_id

        delete service group
        """
        pass

    def test_get_admin_by_id(self):
        """
        Test case for get_admin_by_id

        get admin
        """
        pass

    def test_get_admin_list(self):
        """
        Test case for get_admin_list

        get admin list
        """
        pass

    def test_get_alert_by_id(self):
        """
        Test case for get_alert_by_id

        get alert
        """
        pass

    def test_get_alert_list(self):
        """
        Test case for get_alert_list

        get alert list
        """
        pass

    def test_get_alert_list_by_device_group_id(self):
        """
        Test case for get_alert_list_by_device_group_id

        get device group alerts
        """
        pass

    def test_get_alert_list_by_device_id(self):
        """
        Test case for get_alert_list_by_device_id

        get alerts
        """
        pass

    def test_get_alert_rule_by_id(self):
        """
        Test case for get_alert_rule_by_id

        get alert rule by id
        """
        pass

    def test_get_alert_rule_list(self):
        """
        Test case for get_alert_rule_list

        get alert rule list
        """
        pass

    def test_get_api_token_list_by_admin_id(self):
        """
        Test case for get_api_token_list_by_admin_id

        get apiToken by admin
        """
        pass

    def test_get_collector_by_id(self):
        """
        Test case for get_collector_by_id

        get collector
        """
        pass

    def test_get_collector_group_by_id(self):
        """
        Test case for get_collector_group_by_id

        get collector group
        """
        pass

    def test_get_collector_group_list(self):
        """
        Test case for get_collector_group_list

        get collector group list
        """
        pass

    def test_get_collector_list(self):
        """
        Test case for get_collector_list

        get collector list
        """
        pass

    def test_get_dashboard_by_id(self):
        """
        Test case for get_dashboard_by_id

        get dashboard
        """
        pass

    def test_get_dashboard_group_by_id(self):
        """
        Test case for get_dashboard_group_by_id

        get dashboard group
        """
        pass

    def test_get_dashboard_group_list(self):
        """
        Test case for get_dashboard_group_list

        get dashboard group list
        """
        pass

    def test_get_dashboard_list(self):
        """
        Test case for get_dashboard_list

        get dashboard list
        """
        pass

    def test_get_device_by_id(self):
        """
        Test case for get_device_by_id

        get device by id
        """
        pass

    def test_get_device_datasource_by_id(self):
        """
        Test case for get_device_datasource_by_id

        get device datasource 
        """
        pass

    def test_get_device_datasource_data_by_id(self):
        """
        Test case for get_device_datasource_data_by_id

        get device datasource data 
        """
        pass

    def test_get_device_datasource_instance_alert_setting_by_id(self):
        """
        Test case for get_device_datasource_instance_alert_setting_by_id

        get device instance alert setting
        """
        pass

    def test_get_device_datasource_instance_by_id(self):
        """
        Test case for get_device_datasource_instance_by_id

        get device instance 
        """
        pass

    def test_get_device_datasource_instance_data(self):
        """
        Test case for get_device_datasource_instance_data

        get device instance data
        """
        pass

    def test_get_device_datasource_instance_graph_data(self):
        """
        Test case for get_device_datasource_instance_graph_data

        get device instance graph data 
        """
        pass

    def test_get_device_datasource_instance_group_by_id(self):
        """
        Test case for get_device_datasource_instance_group_by_id

        get device datasource instance group 
        """
        pass

    def test_get_device_datasource_instance_group_overview_graph_data(self):
        """
        Test case for get_device_datasource_instance_group_overview_graph_data

        get device instance group overview graph data 
        """
        pass

    def test_get_device_datasource_list(self):
        """
        Test case for get_device_datasource_list

        get device datasource list 
        """
        pass

    def test_get_device_group_by_id(self):
        """
        Test case for get_device_group_by_id

        get device group
        """
        pass

    def test_get_device_group_datasource_alert_setting(self):
        """
        Test case for get_device_group_datasource_alert_setting

        get device group datasource alert setting 
        """
        pass

    def test_get_device_group_datasource_by_id(self):
        """
        Test case for get_device_group_datasource_by_id

        get device group datasource
        """
        pass

    def test_get_device_group_datasource_list(self):
        """
        Test case for get_device_group_datasource_list

        get device group datasource list
        """
        pass

    def test_get_device_group_list(self):
        """
        Test case for get_device_group_list

        get device group list
        """
        pass

    def test_get_device_group_properties(self):
        """
        Test case for get_device_group_properties

        get device group properties
        """
        pass

    def test_get_device_group_property_by_name(self):
        """
        Test case for get_device_group_property_by_name

        get device group property by name
        """
        pass

    def test_get_device_instance_graph_data_only_by_instance_id(self):
        """
        Test case for get_device_instance_graph_data_only_by_instance_id

        get device instance graphData
        """
        pass

    def test_get_device_list(self):
        """
        Test case for get_device_list

        get device list
        """
        pass

    def test_get_device_properties_list(self):
        """
        Test case for get_device_properties_list

        get device properties
        """
        pass

    def test_get_device_property_by_name(self):
        """
        Test case for get_device_property_by_name

        get device property by name
        """
        pass

    def test_get_immediate_device_list_by_device_group_id(self):
        """
        Test case for get_immediate_device_list_by_device_group_id

        get immediate devices under group
        """
        pass

    def test_get_role_by_id(self):
        """
        Test case for get_role_by_id

        get role by id
        """
        pass

    def test_get_role_list(self):
        """
        Test case for get_role_list

        get role list
        """
        pass

    def test_get_service_graph_data(self):
        """
        Test case for get_service_graph_data

        get service graph data
        """
        pass

    def test_get_service_group_by_id(self):
        """
        Test case for get_service_group_by_id

        get service group
        """
        pass

    def test_get_service_group_list(self):
        """
        Test case for get_service_group_list

        get service group list
        """
        pass

    def test_get_site_monitor_check_point_list(self):
        """
        Test case for get_site_monitor_check_point_list

        get site monitor checkpoint list
        """
        pass

    def test_get_unmonitored_device_list(self):
        """
        Test case for get_unmonitored_device_list

        get unmonitored device list
        """
        pass

    def test_install_collector(self):
        """
        Test case for install_collector

        install collector
        """
        pass

    def test_patch_device_by_id(self):
        """
        Test case for patch_device_by_id

        patch a device
        """
        pass

    def test_patch_device_group_by_id(self):
        """
        Test case for patch_device_group_by_id

        patch device group
        """
        pass

    def test_patch_service_group_by_id(self):
        """
        Test case for patch_service_group_by_id

        patch service group
        """
        pass

    def test_schedule_auto_discovery_by_device_id(self):
        """
        Test case for schedule_auto_discovery_by_device_id

        schedule auto discovery for a host
        """
        pass

    def test_update_admin_by_id(self):
        """
        Test case for update_admin_by_id

        update admin
        """
        pass

    def test_update_alert_rule_by_id(self):
        """
        Test case for update_alert_rule_by_id

        update alert rule
        """
        pass

    def test_update_api_token_by_admin_id(self):
        """
        Test case for update_api_token_by_admin_id

        update apiToken by admin
        """
        pass

    def test_update_collector_by_id(self):
        """
        Test case for update_collector_by_id

        update collector
        """
        pass

    def test_update_collector_group_by_id(self):
        """
        Test case for update_collector_group_by_id

        update collector group
        """
        pass

    def test_update_dashboard_by_id(self):
        """
        Test case for update_dashboard_by_id

        update dashboard
        """
        pass

    def test_update_dashboard_group_by_id(self):
        """
        Test case for update_dashboard_group_by_id

        update dashboard group
        """
        pass

    def test_update_device(self):
        """
        Test case for update_device

        update a device
        """
        pass

    def test_update_device_datasource_instance_alert_setting_by_id(self):
        """
        Test case for update_device_datasource_instance_alert_setting_by_id

        update device instance alert setting
        """
        pass

    def test_update_device_datasource_instance_by_id(self):
        """
        Test case for update_device_datasource_instance_by_id

        update device instance 
        """
        pass

    def test_update_device_datasource_instance_group_by_id(self):
        """
        Test case for update_device_datasource_instance_group_by_id

        update device datasource instance group 
        """
        pass

    def test_update_device_group_by_id(self):
        """
        Test case for update_device_group_by_id

        update device group
        """
        pass

    def test_update_device_group_datasource_alert_setting(self):
        """
        Test case for update_device_group_datasource_alert_setting

        update device group datasource alert setting 
        """
        pass

    def test_update_device_group_property_by_name(self):
        """
        Test case for update_device_group_property_by_name

        update device group property
        """
        pass

    def test_update_device_property_by_name(self):
        """
        Test case for update_device_property_by_name

        update device  property
        """
        pass

    def test_update_role_by_id(self):
        """
        Test case for update_role_by_id

        update role
        """
        pass

    def test_update_service_group_by_id(self):
        """
        Test case for update_service_group_by_id

        update service group
        """
        pass


if __name__ == '__main__':
    unittest.main()
