# coding: utf-8

"""
    LogicMonitor REST API

    LogicMonitor is a SaaS-based performance monitoring platform that provides full visibility into complex, hybrid infrastructures, offering granular performance monitoring and actionable data and insights. logicmonitor_sdk enables you to manage your LogicMonitor account programmatically.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import logicmonitor_sdk
from logicmonitor_sdk.models.azure_rss_event_source import AzureRssEventSource  # noqa: E501
from logicmonitor_sdk.rest import ApiException


class TestAzureRssEventSource(unittest.TestCase):
    """AzureRssEventSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureRssEventSource(self):
        """Test AzureRssEventSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = logicmonitor_sdk.models.azure_rss_event_source.AzureRssEventSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
