# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import logicmonitor
from logicmonitor.rest import ApiException
from logicmonitor.models.manual_discovery_flags import ManualDiscoveryFlags


class TestManualDiscoveryFlags(unittest.TestCase):
    """ ManualDiscoveryFlags unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManualDiscoveryFlags(self):
        """
        Test ManualDiscoveryFlags
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = logicmonitor.models.manual_discovery_flags.ManualDiscoveryFlags()
        pass


if __name__ == '__main__':
    unittest.main()
