# coding: utf-8

"""
    LogicMonitor REST API

    LogicMonitor is a SaaS-based performance monitoring platform that provides full visibility into complex, hybrid infrastructures, offering granular performance monitoring and actionable data and insights. logicmonitor_sdk enables you to manage your LogicMonitor account programmatically. <br> <br> Note: <ul> <li> For Python SDKs, the REQUEST parameters can contain camelCase or an underscore. </li> <li> Both underscore and camelCase are supported if parameters are encapsulated within the body. </li> <li> Only camelCase is supported if parameters are encapsulated within the body and also if the user is passing raw JSON as REQUEST parameter. However, the RESPONSE parameters always contain an underscore. For example, you can use testLocation or test_location in the REQUEST parameter. But the RESPONSE parameter will always be test_location. </li> <li> The fields parameter only supports camelCase. </li> </ul>  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DashboardFilterDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mode': 'str',
        'field': 'str',
        'type': 'str',
        'expressions': 'list[DashboardFilterExpressions]'
    }

    attribute_map = {
        'mode': 'mode',
        'field': 'field',
        'type': 'type',
        'expressions': 'expressions'
    }

    def __init__(self, mode=None, field=None, type=None, expressions=None):  # noqa: E501
        """DashboardFilterDetails - a model defined in Swagger"""  # noqa: E501
        self._mode = None
        self._field = None
        self._type = None
        self._expressions = None
        self.discriminator = None
        if mode is not None:
            self.mode = mode
        if field is not None:
            self.field = field
        if type is not None:
            self.type = type
        if expressions is not None:
            self.expressions = expressions

    @property
    def mode(self):
        """Gets the mode of this DashboardFilterDetails.  # noqa: E501


        :return: The mode of this DashboardFilterDetails.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this DashboardFilterDetails.


        :param mode: The mode of this DashboardFilterDetails.  # noqa: E501
        :type: str
        """

        self._mode = mode

    @property
    def field(self):
        """Gets the field of this DashboardFilterDetails.  # noqa: E501


        :return: The field of this DashboardFilterDetails.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this DashboardFilterDetails.


        :param field: The field of this DashboardFilterDetails.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def type(self):
        """Gets the type of this DashboardFilterDetails.  # noqa: E501


        :return: The type of this DashboardFilterDetails.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DashboardFilterDetails.


        :param type: The type of this DashboardFilterDetails.  # noqa: E501
        :type: str
        """
        allowed_values = ["RESOURCE_PROPERTY", "INSTANCE_PROPERTY"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def expressions(self):
        """Gets the expressions of this DashboardFilterDetails.  # noqa: E501


        :return: The expressions of this DashboardFilterDetails.  # noqa: E501
        :rtype: list[DashboardFilterExpressions]
        """
        return self._expressions

    @expressions.setter
    def expressions(self, expressions):
        """Sets the expressions of this DashboardFilterDetails.


        :param expressions: The expressions of this DashboardFilterDetails.  # noqa: E501
        :type: list[DashboardFilterExpressions]
        """

        self._expressions = expressions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DashboardFilterDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DashboardFilterDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
